# Generated by Django 3.2.4 on 2021-06-22 08:53

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_alter_customusermodel_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customusermodel',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
