# Generated by Django 3.2.4 on 2021-06-22 08:55

import accounts_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_alter_customusermodel_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusermodel',
            options={'ordering': ['username'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelManagers(
            name='customusermodel',
            managers=[
                ('objects', accounts_app.models.CustomUserManager()),
            ],
        ),
    ]
